// <auto-generated />
using System;
using IntegrationSimulator.IntegrationService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegrationSimulator.IntegrationService.Infrastructure.Migrations
{
    [DbContext(typeof(JobAdsMetaDataContext))]
    partial class JobAdsMetaDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("IntegrationSimulator.IntegrationService.Infrastructure.Persistence.Entities.JobAdsMetaData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LatestSuccessfulFetch")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MetaData");
                });
#pragma warning restore 612, 618
        }
    }
}
