services:
  integration-service:
    image: josephrashidmaalouf/integration-service:latest
    container_name: integration-service
    volumes:
      - integration_data:/app/Data    
      - integration_logs:/app/Logs     
    environment:
      - DOTNET_ENVIRONMENT=docker
    pull_policy: always

  fake-erp:
    image: josephrashidmaalouf/fake-erp:latest
    container_name: fake-erp
    ports:
      - "5000:5000"
    volumes:
      - fake_erp_data:/app           
    pull_policy: always

  rabbit-mq:
    image: "rabbit:3-management"
    container_name: "rabbit-mq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  integration_data:
  integration_logs:
  fake_erp_data:
  rabbitmq_data: