<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IntegrationSimulator.IntegrationService.Domain\IntegrationSimulator.IntegrationService.Domain.csproj" />
  </ItemGroup>

</Project>
